name: Deploy AdonisJS 6

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "\
            cd /var/www/html/live_chat && \
            git pull origin main && \
            chmod +x deploy.sh && \
            ./deploy.sh \
          "